### ISSUE TITLE
Connect to SAP HANA, express edition using Python

### ISSUE THREAD

**Issue by Paddre** [SAPDocuments/How-Tos#245]
In Step 3: Test Connectivity

The example code fails at line `from hdbcli import dbapi` with error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\sap\hdbclient\hdbcli\dbapi.py", line 12, in <module>
    import pyhdbcli
ImportError: DLL load failed: The specified module could not be found.

**Comment by Paddre** [comment]
Sorry, my bad. I tried executing the code from within the python console and then got the above error. Saving it in a .py file as described in the How-To, works fine (except that the connection cannot be established but that's not an issue of the how-to obviously :-P)
